package ru.stqa.pft.art_team.tests;// Generated by Selenium IDE

import org.junit.After;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class TestLogin extends TestBase {

  String users = "users.json";

  @BeforeMethod
  public void go_to_art_team() {
    app.getBaseHelper().go_to_url(app.getBaseHelper().read_json(users, "main_url"));
  }

  @Test
  public void test_login_incorrect_username() {
    app.getSessionHelper().login(app.getBaseHelper().read_json(users,"false_username"),
            app.getBaseHelper().read_json(users,"false_password"));
    app.getSessionHelper().validate_login_invalid_message();
  }

  @Test
  public void test_login_incorrect_password() {
    app.getSessionHelper().login(app.getBaseHelper().read_json(users,"username"),
            app.getBaseHelper().read_json(users,"false_password"));
    app.getSessionHelper().validate_login_invalid_message();
  }

  @Test
  public void test_login_success() {
    app.getSessionHelper().login(app.getBaseHelper().read_json(users,"username"),
            app.getBaseHelper().read_json(users,"password"));
    app.getSessionHelper().validate_exit_button();
    app.getBaseHelper().press_exit_button();
  }

}
